//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexMichaelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.purchases = new HashSet<purchase>();
            this.manufacturers = new HashSet<manufacturer>();
        }
    
        public string product1 { get; set; }
        public string type { get; set; }
        public string manufacturer { get; set; }
        public string clubName { get; set; }
        public int cost { get; set; }
        public int size { get; set; }
        public string description { get; set; }
        public byte[] photo { get; set; }
    
        public virtual manufacturer manufacturer1 { get; set; }
        public virtual team team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manufacturer> manufacturers { get; set; }
    }
}
