//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexMichaelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public string username { get; set; }
        public string product { get; set; }
        public int creditcardnumber { get; set; }
        public System.DateTime dateOfPurchase { get; set; }
        public int dealID { get; set; }
    
        public virtual paymentoption paymentoption { get; set; }
        public virtual product product1 { get; set; }
        public virtual user user { get; set; }
    }
}
