//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexMichaelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ticketID { get; set; }
        public int matchID { get; set; }
        public int seatNumber { get; set; }
        public int cost { get; set; }
        public string seatType { get; set; }
    
        public virtual match match { get; set; }
    }
}
